### ISSUE TITLE
Boundary effect of recovered spikes

### ISSUE THREAD

**Issue by titipata** [KordingLab/nerds#5]
We found the boundary effect of recovered spike train i.e. we tend to have excess spikes at the end of prediction. We are trying to see where in the code that give rise to this issue.

**Comment by DylanMuir** [comment]
I have found that padding the end of the source trace with zeros, to around 10% of the original length of the trace, and then trimming the end of the estimated spike trace by the same amount, mostly 
avoids the problem.

**Comment by DylanMuir** [comment]
#8
