### ISSUE TITLE
Use of `private` subdirectory

### ISSUE THREAD

**Issue by DylanMuir** [KordingLab/nerds#6]
I suggest that you move all functions from `utilities` and `spgl1_extend` directories to a new `private` directory. Matlab automatically discovers these functions without having to add the `private` directory to the matlab path, and as an added benefit, these functions are hidden from use except by `nerds`.

**Comment by titipata** [comment]
Thanks so much @DylanMuir! Do you have the working version where you move `utilities` and `spgl1_extend` inside `private` folder? I can do a pull request if you have that already.

**Comment by DylanMuir** [comment]
#7

**Comment by titipata** [comment]
closed thanks to @DylanMuir PR.
